spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.128:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Xiao1314!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    root: warn
    com.java.blog: info
  file:
    name: log/blog-pro.log
server:
  port: 8080